// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABXyxGWeJxamVW9BNoBMrSwrKIySJtFLw',
    appId: '1:733865907673:web:3f641095ebfebef56d35c8',
    messagingSenderId: '733865907673',
    projectId: 'cafefinder-eafdf',
    authDomain: 'cafefinder-eafdf.firebaseapp.com',
    storageBucket: 'cafefinder-eafdf.firebasestorage.app',
    measurementId: 'G-5C4EXXG1T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrOtXtG-4FWubyA5avTlcsEi4fkj6ROqU',
    appId: '1:733865907673:android:5bba8385237d6d3a6d35c8',
    messagingSenderId: '733865907673',
    projectId: 'cafefinder-eafdf',
    storageBucket: 'cafefinder-eafdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgKSXU9YOaSRMW8zXGyOEz72V7q0xK-Y',
    appId: '1:733865907673:ios:51adf9a9ef7008e16d35c8',
    messagingSenderId: '733865907673',
    projectId: 'cafefinder-eafdf',
    storageBucket: 'cafefinder-eafdf.firebasestorage.app',
    iosBundleId: 'com.example.cafefindhyd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPgKSXU9YOaSRMW8zXGyOEz72V7q0xK-Y',
    appId: '1:733865907673:ios:51adf9a9ef7008e16d35c8',
    messagingSenderId: '733865907673',
    projectId: 'cafefinder-eafdf',
    storageBucket: 'cafefinder-eafdf.firebasestorage.app',
    iosBundleId: 'com.example.cafefindhyd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABXyxGWeJxamVW9BNoBMrSwrKIySJtFLw',
    appId: '1:733865907673:web:a7e92ab4af6ef80f6d35c8',
    messagingSenderId: '733865907673',
    projectId: 'cafefinder-eafdf',
    authDomain: 'cafefinder-eafdf.firebaseapp.com',
    storageBucket: 'cafefinder-eafdf.firebasestorage.app',
    measurementId: 'G-JKL5JEKJXG',
  );
}
